# Generated by Django 3.0.8 on 2020-07-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('cod_vendedor', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('cod_tab', models.IntegerField()),
                ('data_nasc', models.DateField()),
            ],
        ),
    ]
