# Generated by Django 3.0.8 on 2020-07-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=17)),
                ('cod_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.Vendedor')),
            ],
        ),
    ]
