# Generated by Django 3.0.8 on 2020-07-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0003_auto_20200718_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cod_vendedor',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
